import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  Archive, BookOpen, Boxes, Camera, Check, ChevronRight, Clock3, Eye, GitBranch, GitCompare,
  Globe2, Grid2X2, Image, ListFilter, Maximize2, Network, PanelLeftClose, PanelLeftOpen,
  PanelRightClose, PanelRightOpen, Pencil, Plus, Search, Sparkles, Table2, Trash2, Waypoints,
  WandSparkles, X,
} from "lucide-react";
import { studioApi } from "../api";
import type { EntityFamily, EntityVariant, JsonMap, MediaItem, Relationship, Selection, WorldBible } from "../types";

interface LibraryViewProps {
  projectId: string; worldId: string; branchId: string; bible: WorldBible | null; entityTypes: string[];
  onChanged: () => Promise<void> | void; onSelect: (selection: Selection) => void;
}
type ObjectLayout = "table" | "grid" | "gallery";
type ObjectFilter = "all" | "missing-media" | "draft";
const OBJECT_TABS = [["all", "All objects"], ["character", "Characters"], ["location", "Locations"], ["item", "Items"], ["organization", "Organizations"], ["lore", "Lore"]] as const;
const KNOWLEDGE_TABS = [["canon", "Canon"], ["relationships", "Relationships"], ["timeline", "Timeline"]] as const;
const STRUCTURE_TABS = [["worlds", "Worlds & branches"]] as const;

export function LibraryView({ projectId, worldId, branchId, bible, entityTypes, onChanged, onSelect }: LibraryViewProps) {
  const [tab, setTab] = useState("all");
  const [query, setQuery] = useState("");
  const [layout, setLayout] = useState<ObjectLayout>("grid");
  const [objectFilter, setObjectFilter] = useState<ObjectFilter>("all");
  const [sortOrder, setSortOrder] = useState<"name" | "type">("name");
  const [focused, setFocused] = useState<Selection | null>(null);
  const [peek, setPeek] = useState<Selection | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const [railCollapsed, setRailCollapsed] = useState(() => localStorage.getItem("arline.library.rail") === "collapsed");
  const [inspectorCollapsed, setInspectorCollapsed] = useState(() => localStorage.getItem("arline.library.inspector") === "collapsed");
  const [mobileRailOpen, setMobileRailOpen] = useState(false);
  const [quickOpen, setQuickOpen] = useState(false);
  const [quickText, setQuickText] = useState("");
  const [quickKind, setQuickKind] = useState("");
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [media, setMedia] = useState<MediaItem[]>([]);
  const [timeline, setTimeline] = useState<JsonMap[]>([]);
  const [facts, setFacts] = useState<JsonMap[]>([]);
  const [snapshots, setSnapshots] = useState<JsonMap[]>([]);
  const families = bible?.families || [];
  const variants = bible?.variants || [];
  const relationships = bible?.relationships || [];
  const worlds = bible?.worlds || [];

  useEffect(() => localStorage.setItem("arline.library.rail", railCollapsed ? "collapsed" : "open"), [railCollapsed]);
  useEffect(() => localStorage.setItem("arline.library.inspector", inspectorCollapsed ? "collapsed" : "open"), [inspectorCollapsed]);
  useEffect(() => {
    if (!worldId) return;
    void Promise.all([
      studioApi.media({ coverOnly: true }).catch(() => ({ items: [] })),
      studioApi.timeline(worldId, branchId).catch(() => ({ events: [] })),
      studioApi.facts(projectId, worldId, branchId).catch(() => ({ facts: [] })),
      studioApi.snapshots(worldId).catch(() => ({ snapshots: [] })),
    ]).then(([mediaResult, timelineResult, factResult, snapshotResult]) => {
      setMedia(mediaResult.items || []); setTimeline(timelineResult.events || []);
      setFacts(factResult.facts || []); setSnapshots(snapshotResult.snapshots || []);
    });
  }, [projectId, worldId, branchId]);

  const variantFor = (family: EntityFamily): EntityVariant | undefined => variants.find((variant) => variant.family_id === family.id && (!worldId || variant.world_id === worldId));
  const coverFor = (family: EntityFamily) => media.find((item) => item.resource_type === "entity_family" && item.resource_id === family.id);
  const filteredFamilies = useMemo(() => families.filter((family) => {
    if (tab !== "all" && family.entity_type !== tab) return false;
    if (objectFilter === "missing-media" && coverFor(family)) return false;
    if (objectFilter === "draft" && variantFor(family)?.canon_status !== "draft") return false;
    const needle = query.trim().toLowerCase();
    return !needle || family.name.toLowerCase().includes(needle) || family.description?.toLowerCase().includes(needle);
  }).sort((a, b) => sortOrder === "type" ? String(a.entity_type).localeCompare(String(b.entity_type)) || a.name.localeCompare(b.name) : a.name.localeCompare(b.name)), [families, variants, media, tab, query, objectFilter, sortOrder]);

  const section = useMemo(() => {
    if (tab === "canon") return { eyebrow: "World state", title: "Canon", status: `${facts.length} facts · ${facts.filter((fact) => fact.status === "draft").length} drafts`, create: "Fact", placeholder: "Search canon facts" };
    if (tab === "relationships") return { eyebrow: "Connected knowledge", title: "Relationships", status: `${relationships.length} edges across the active world`, create: "Relationship", placeholder: "Search relationships" };
    if (tab === "timeline") return { eyebrow: "Temporal state", title: "Timeline", status: `${timeline.length} events · active world and branch`, create: "Event", placeholder: "Search timeline" };
    if (tab === "worlds") return { eyebrow: "Structure", title: "Worlds & branches", status: `${worlds.length} worlds · ${worlds.reduce((sum, world) => sum + (world.branches?.length || 0), 0)} branches`, create: "World", placeholder: "Search worlds" };
    const label = OBJECT_TABS.find(([value]) => value === tab)?.[1] || "All objects";
    return { eyebrow: "Shared knowledge", title: label, status: `${filteredFamilies.length} objects · ${filteredFamilies.filter((family) => !coverFor(family)).length} without cover`, create: tab === "all" ? "Object" : label.replace(/s$/, ""), placeholder: `Search ${label.toLowerCase()}` };
  }, [tab, facts, relationships, timeline, worlds, filteredFamilies, media]);

  const entitySelection = (family: EntityFamily): Selection => {
    const variant = variantFor(family);
    return { kind: "entity", id: family.id, title: variant?.display_name || family.name, subtitle: family.entity_type || "entity", data: { family, variant } };
  };
  const relationshipSelection = (relationship: Relationship): Selection => ({ kind: "relationship", id: relationship.id, title: `${relationship.subject_name || "Entity"} → ${relationship.object_name || "Entity"}`, subtitle: relationship.relation_type || "relationship", data: relationship });
  const selectItem = (selection: Selection) => { setFocused(selection); setInspectorCollapsed(false); };
  const setSection = (value: string) => { setTab(value); setQuery(""); setNotice(""); setMobileRailOpen(false); };
  const addFocusedToContext = async () => {
    if (!focused?.id) return;
    await studioApi.pinContext({ project_id: projectId, world_id: worldId || null, branch_id: branchId || null, resource_type: focused.kind === "entity" ? "entity_family" : focused.kind, resource_id: focused.id, scope: "world", priority: 1 });
    setNotice(`${focused.title} added to Chat context`);
  };
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.matches("input, textarea, select, [contenteditable='true']") || quickOpen) return;
      if (event.key === "Escape") { if (peek) setPeek(null); else setFocused(null); return; }
      if (!focused) return;
      if (event.key === " ") { event.preventDefault(); setPeek(focused); }
      if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); void addFocusedToContext(); }
      else if (event.key === "Enter") { event.preventDefault(); onSelect(focused); }
      if ((event.key === "ArrowDown" || event.key === "ArrowUp") && focused.kind === "entity") {
        const index = filteredFamilies.findIndex((family) => family.id === focused.id);
        const next = filteredFamilies[index + (event.key === "ArrowDown" ? 1 : -1)];
        if (next) { event.preventDefault(); setFocused(entitySelection(next)); }
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [focused, peek, quickOpen, filteredFamilies]);

  const runLibraryAction = async (label: string, action: () => Promise<unknown>) => {
    setBusy(true); setNotice("");
    try { await action(); setNotice(`${label} complete`); await onChanged(); }
    catch (error) { setNotice((error as Error).message); }
    finally { setBusy(false); }
  };
  const createForTab = async () => {
    if (tab === "timeline") { const summary = window.prompt("Timeline event"); if (!summary) return; await runLibraryAction("Timeline event", () => studioApi.createTimelineEvent({ world_id: worldId, branch_id: branchId || null, summary, time_label: window.prompt("Time label", "") || "", order_key: timeline.length + 1, event_type: "event", state_patch: {}, status: "canon" })); setTimeline((await studioApi.timeline(worldId, branchId)).events || []); return; }
    if (tab === "canon") { const path = window.prompt("Semantic path", "world.rule"); if (!path) return; const value = window.prompt("Fact value", ""); if (value === null) return; await runLibraryAction("Canon fact", () => studioApi.createFact({ project_id: projectId, world_id: worldId, branch_id: branchId || null, owner_type: "world", owner_id: worldId, path, value, status: "canon", authority: "user_explicit" })); setFacts((await studioApi.facts(projectId, worldId, branchId)).facts || []); return; }
    if (tab === "worlds") { const name = window.prompt("World name"); if (name) await runLibraryAction("World created", () => studioApi.createWorld({ project_id: projectId, name, description: "", canon_status: "draft", inheritance_mode: "snapshot", clone_parent: true })); return; }
    if (tab === "relationships") { const subject = window.prompt("Subject variant ID"); const object = window.prompt("Object variant ID"); const relationType = window.prompt("Relationship type", "related_to"); if (subject && object && relationType) await runLibraryAction("Relationship created", () => studioApi.createRelationship({ world_id: worldId, branch_id: branchId || null, subject_variant_id: subject, object_variant_id: object, relation_type: relationType, canon_status: "draft", attributes: {} })); return; }
    setQuickKind(tab === "all" ? "entity" : `entity:${tab}`); setQuickOpen(true);
  };
  const previewQuickCreate = async () => { if (!quickText.trim()) return; setBusy(true); try { setPreview(await studioApi.quickCreatePreview({ text: quickText.trim(), forced_kind: quickKind || null, project_id: projectId || null, world_id: worldId || null, branch_id: branchId || null, folder_id: null })); } finally { setBusy(false); } };
  const createQuick = async () => { if (!quickText.trim()) return; setBusy(true); try { await studioApi.quickCreate({ text: quickText.trim(), forced_kind: quickKind || null, project_id: projectId || null, world_id: worldId || null, branch_id: branchId || null, folder_id: null }); setQuickOpen(false); setQuickText(""); setPreview(null); await onChanged(); } finally { setBusy(false); } };
  const toggleSelected = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const editFamily = async (family: EntityFamily) => { const name = window.prompt("Sheet name", family.name); if (!name) return; const description = window.prompt("Description", family.description || ""); if (description !== null) await runLibraryAction("Sheet updated", () => studioApi.updateEntityFamily(family.id, { name, description, note: "edited in React Library" })); };
  const uploadCover = async (family: EntityFamily) => { const input = document.createElement("input"); input.type = "file"; input.accept = "image/*"; input.onchange = () => { const file = input.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { await studioApi.createMedia({ resource_type: "entity_family", resource_id: family.id, filename: file.name, data_url: String(reader.result), kind: "reference", caption: family.name, is_cover: true }); setMedia((await studioApi.media({ coverOnly: true })).items || []); }; reader.readAsDataURL(file); }; input.click(); };
  const saveView = async () => { const name = window.prompt("Saved view name", section.title); if (name) { await studioApi.createSavedView({ name, scope_type: "world_bible", scope_id: worldId, resource_type: tab, query: { text: query, tab, layout, filter: objectFilter, sort: sortOrder } }); await onChanged(); setNotice(`Saved view “${name}” created`); } };
  const applySavedView = (item: JsonMap) => { const saved = (item.query || {}) as JsonMap; setTab(String(saved.tab || item.resource_type || "all")); setQuery(String(saved.text || "")); if (["table", "grid", "gallery"].includes(String(saved.layout))) setLayout(String(saved.layout) as ObjectLayout); if (["all", "missing-media", "draft"].includes(String(saved.filter))) setObjectFilter(String(saved.filter) as ObjectFilter); if (["name", "type"].includes(String(saved.sort))) setSortOrder(String(saved.sort) as "name" | "type"); };
  const compareBranches = async () => { const other = worlds.find((world) => world.id === worldId)?.branches?.find((branch) => branch.id !== branchId); if (!other) return setNotice("Create another branch before comparing."); onSelect({ kind: "analysis", title: "Branch comparison", data: await studioApi.compareBranches(branchId, other.id) }); };
  const compareWorlds = async () => { const other = worlds.find((world) => world.id !== worldId); if (!other) return setNotice("Create another world before comparing."); onSelect({ kind: "analysis", title: "World comparison", data: await studioApi.compareWorlds(worldId, other.id) }); };
  const savedViews = (bible?.saved_views || []) as JsonMap[];

  return <div className={`library-layout ${railCollapsed ? "rail-collapsed" : ""} ${inspectorCollapsed ? "inspector-collapsed" : ""} ${focused ? "has-focus" : ""} ${mobileRailOpen ? "mobile-rail-open" : ""}`}>
    <aside className="library-rail">
      <div className="pane-heading"><div><span className="eyebrow">Library</span><h2>{railCollapsed ? "" : "Navigate"}</h2></div><button className="icon-control" title={railCollapsed ? "Expand Library navigator" : "Collapse Library navigator"} onClick={() => window.innerWidth <= 700 ? setMobileRailOpen(false) : setRailCollapsed((value) => !value)}>{railCollapsed ? <PanelLeftOpen size={14} /> : <PanelLeftClose size={14} />}</button></div>
      {!railCollapsed && <><button className={`library-rail-root ${tab === "all" ? "active" : ""}`} onClick={() => setSection("all")}><BookOpen size={14} />All Library</button><SemanticNav title="Objects" items={OBJECT_TABS.slice(1)} active={tab} onSelect={setSection} /><SemanticNav title="Knowledge" items={KNOWLEDGE_TABS} active={tab} onSelect={setSection} /><SemanticNav title="Structure" items={STRUCTURE_TABS} active={tab} onSelect={setSection} />
        <RailGroup title="Folders" items={(bible?.folder_tree || bible?.folders || []).map((item) => String(item.name || "Folder"))} empty="No Library folders yet." onAdd={async () => { const name = window.prompt("Folder name"); if (name) { await studioApi.createFolder({ project_id: projectId, name, world_id: worldId || null, branch_id: branchId || null, kind: "world_bible" }); await onChanged(); } }} />
        <RailGroup title="Collections" items={(bible?.collections || []).map((item) => String(item.name || item.title || "Collection"))} empty="No collections yet." onAdd={async () => { const name = window.prompt("Collection name"); if (name) { await studioApi.createCollection({ name, scope_type: "world_bible", scope_id: worldId }); await onChanged(); } }} />
        <section className="library-rail-group"><div className="library-rail-title"><span>Saved views</span><button title="Save current view" onClick={() => void saveView()}>＋</button></div>{savedViews.length ? savedViews.slice(0, 8).map((item, index) => <button key={String(item.id || index)} className="library-rail-item saved-view-item" onClick={() => applySavedView(item)}><Sparkles size={11} />{String(item.name || item.title || "Saved view")}</button>) : <p>No saved views yet.</p>}</section></>}
    </aside>
    <section className="library-main">
      <button className="mobile-library-nav" onClick={() => setMobileRailOpen(true)}><PanelLeftOpen size={14} />Browse Library</button><div className="library-workspace-header"><div><span className="eyebrow">{section.eyebrow}</span><h1>{section.title}</h1><p>{section.status}</p></div><div className="library-actions">{tab === "canon" && <button className="secondary-action" onClick={async () => onSelect({ kind: "analysis", title: "Continuity report", data: await studioApi.continuity(projectId, worldId, branchId) })}><WandSparkles size={14} />Continuity</button>}{tab === "worlds" && <><button className="secondary-action" onClick={() => void compareBranches()}><GitCompare size={14} />Branches</button><button className="secondary-action" onClick={() => void compareWorlds()}><GitCompare size={14} />Worlds</button><button className="secondary-action" onClick={() => runLibraryAction("Snapshot", () => studioApi.snapshot({ project_id: projectId, world_id: worldId, branch_id: branchId }))}><Camera size={14} />Snapshot</button></>}<button className="primary-action" onClick={() => void createForTab()}><Plus size={14} />{section.create}</button></div></div>
      <div className="library-toolbar semantic-toolbar"><label className="library-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={section.placeholder} /></label>{!["canon", "relationships", "timeline", "worlds"].includes(tab) ? <><select className="library-select" value={objectFilter} onChange={(event) => setObjectFilter(event.target.value as ObjectFilter)}><option value="all">All details</option><option value="missing-media">Missing cover</option><option value="draft">Draft only</option></select><select className="library-select" value={sortOrder} onChange={(event) => setSortOrder(event.target.value as "name" | "type")}><option value="name">Sort: Name</option><option value="type">Sort: Type</option></select><button className="toolbar-action" onClick={() => void saveView()}><Sparkles size={13} />Save view</button><div className="view-toggle"><button className={layout === "table" ? "active" : ""} onClick={() => setLayout("table")} title="Table view"><Table2 size={14} /></button><button className={layout === "grid" ? "active" : ""} onClick={() => setLayout("grid")} title="Grid view"><Grid2X2 size={14} /></button><button className={layout === "gallery" ? "active" : ""} onClick={() => setLayout("gallery")} title="Gallery view"><Image size={14} /></button></div></> : <span className="toolbar-context">{tab === "relationships" ? <Network size={13} /> : tab === "timeline" ? <Clock3 size={13} /> : tab === "worlds" ? <Globe2 size={13} /> : <ListFilter size={13} />}{tab === "relationships" ? "List · readable edges" : tab === "timeline" ? "Chronological · active branch" : tab === "worlds" ? "World tree · branches and snapshots" : "Facts · authority and status"}</span>}</div>
      {objectFilter !== "all" && !["canon", "relationships", "timeline", "worlds"].includes(tab) && <div className="filter-chips"><button onClick={() => setObjectFilter("all")}>{objectFilter === "missing-media" ? "Cover: Missing" : "Status: Draft"}<X size={11} /></button><span>Saved Views remember this filter.</span></div>}
      {notice && <div className="library-notice">{notice}</div>}
      {selected.length > 0 && <BulkBar selected={selected} busy={busy} setSelected={setSelected} run={runLibraryAction} onChanged={onChanged} onSelect={onSelect} />}
      {tab === "relationships" ? <RelationshipList items={relationships} query={query} focused={focused} selectItem={selectItem} open={onSelect} /> : tab === "canon" ? <CanonTable facts={facts} query={query} focused={focused} selectItem={selectItem} open={onSelect} projectId={projectId} worldId={worldId} branchId={branchId} /> : tab === "timeline" ? <TimelineList timeline={timeline} query={query} focused={focused} selectItem={selectItem} open={onSelect} /> : tab === "worlds" ? <WorldList worlds={worlds} snapshots={snapshots} query={query} focused={focused} worldId={worldId} selectItem={selectItem} open={onSelect} run={runLibraryAction} onChanged={onChanged} setSnapshots={setSnapshots} /> : <ObjectBrowser families={filteredFamilies} layout={layout} focusedId={focused?.id} selected={selected} variantFor={variantFor} coverFor={coverFor} onFocus={(family) => selectItem(entitySelection(family))} onOpen={(family) => onSelect(entitySelection(family))} onEdit={editFamily} onToggle={toggleSelected} onCover={uploadCover} />}
    </section>
    <aside className="library-inspector"><div className="library-inspector-header"><div><span className="eyebrow">Inspector</span>{!inspectorCollapsed && <h2>{focused?.title || "Nothing selected"}</h2>}</div><button className="icon-control" title={inspectorCollapsed ? "Expand Inspector" : "Collapse Inspector"} onClick={() => setInspectorCollapsed((value) => !value)}>{inspectorCollapsed ? <PanelRightOpen size={14} /> : <PanelRightClose size={14} />}</button></div>{!inspectorCollapsed && (focused ? <LibraryInspector selection={focused} onOpen={() => onSelect(focused)} onPeek={() => setPeek(focused)} onContext={() => void addFocusedToContext()} /> : <div className="library-inspector-empty"><Eye size={23} /><strong>Select to inspect</strong><p>Single-click any Library record. Nothing is added to Chat automatically.</p></div>)}</aside>
    {peek && <div className="library-peek-backdrop" onMouseDown={() => setPeek(null)}><section className="library-peek" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">Quick peek</span><h2>{peek.title}</h2><p>{peek.subtitle || peek.kind}</p></div><button className="icon-control" onClick={() => setPeek(null)}><X size={15} /></button></header><LibraryInspector selection={peek} compact onOpen={() => onSelect(peek)} onPeek={() => setPeek(null)} onContext={() => void addFocusedToContext()} /></section></div>}
    {quickOpen && <QuickCreate open={quickOpen} close={() => setQuickOpen(false)} text={quickText} setText={(value) => { setQuickText(value); setPreview(null); }} kind={quickKind} setKind={setQuickKind} entityTypes={entityTypes} preview={preview} busy={busy} previewAction={previewQuickCreate} createAction={createQuick} />}
  </div>;
}

function SemanticNav({ title, items, active, onSelect }: { title: string; items: readonly (readonly [string, string])[]; active: string; onSelect: (value: string) => void }) { return <section className="semantic-nav"><h3>{title}</h3>{items.map(([value, label]) => <button key={value} className={active === value ? "active" : ""} onClick={() => onSelect(value)}><span>{label}</span><ChevronRight size={11} /></button>)}</section>; }
function RailGroup({ title, items, empty, onAdd }: { title: string; items: string[]; empty: string; onAdd: () => Promise<void> | void }) { return <section className="library-rail-group"><div className="library-rail-title"><span>{title}</span><button title={`Add ${title.toLowerCase()}`} onClick={() => void onAdd()}>＋</button></div>{items.length ? items.slice(0, 8).map((item) => <button key={item} className="library-rail-item">{item}</button>) : <p>{empty}</p>}</section>; }
function SemanticEmpty({ icon, title, copy }: { icon: ReactNode; title: string; copy: string }) { return <div className="center-empty grid-empty">{icon}<h2>{title}</h2><p>{copy}</p></div>; }

function ObjectBrowser({ families, layout, focusedId, selected, variantFor, coverFor, onFocus, onOpen, onEdit, onToggle, onCover }: { families: EntityFamily[]; layout: ObjectLayout; focusedId?: string; selected: string[]; variantFor: (family: EntityFamily) => EntityVariant | undefined; coverFor: (family: EntityFamily) => MediaItem | undefined; onFocus: (family: EntityFamily) => void; onOpen: (family: EntityFamily) => void; onEdit: (family: EntityFamily) => Promise<void>; onToggle: (id: string) => void; onCover: (family: EntityFamily) => Promise<void> }) {
  if (!families.length) return <SemanticEmpty icon={<Boxes size={26} />} title="No matching objects" copy="Create an object or adjust the current search and filters." />;
  if (layout === "table") return <div className="object-table-wrap"><table className="library-table object-table"><thead><tr><th></th><th>Name</th><th>Type</th><th>Status</th><th>Summary</th><th>Media</th></tr></thead><tbody>{families.map((family) => { const variant = variantFor(family); const cover = coverFor(family); return <tr key={family.id} className={focusedId === family.id ? "active" : ""} onClick={() => onFocus(family)} onDoubleClick={() => onOpen(family)}><td><button className={`table-select ${selected.includes(family.id) ? "selected" : ""}`} onClick={(event) => { event.stopPropagation(); onToggle(family.id); }}>{selected.includes(family.id) ? <Check size={11} /> : null}</button></td><td><strong>{variant?.display_name || family.name}</strong></td><td>{family.entity_type || "entity"}</td><td><span className={`status-pill ${variant?.canon_status || "shared"}`}>{variant?.canon_status || "shared"}</span></td><td>{variant?.summary || family.description || "Shared Library sheet"}</td><td>{cover ? "Cover" : <button className="text-action" onClick={(event) => { event.stopPropagation(); void onCover(family); }}>Add cover</button>}</td></tr>; })}</tbody></table></div>;
  return <div className={`entity-grid view-${layout}`}>{families.map((family) => { const variant = variantFor(family); const cover = coverFor(family); return <button key={family.id} className={`${selected.includes(family.id) ? "selected" : ""} ${focusedId === family.id ? "focused" : ""}`} onClick={() => onFocus(family)} onDoubleClick={() => onOpen(family)} onContextMenu={(event) => { event.preventDefault(); onToggle(family.id); }} title="Select · double-click to open · right-click for bulk selection">{layout === "gallery" && cover?.content_url ? <img className="entity-cover" src={cover.content_url} alt={cover.caption || family.name} /> : null}<span className="entity-select" onClick={(event) => { event.stopPropagation(); onToggle(family.id); }}>{selected.includes(family.id) ? <Check size={12} /> : ""}</span><span className={`entity-type-mark ${family.entity_type || "entity"}`}><Boxes size={16} /></span><span className="entity-kind">{family.entity_type || "entity"}</span><strong>{variant?.display_name || family.name}</strong><p>{variant?.summary || family.description || "Shared Library sheet"}</p><div><small>{variant?.canon_status || "shared"}</small><em onClick={(event) => { event.stopPropagation(); void onCover(family); }}>{cover ? "replace cover" : "add cover"}</em></div></button>; })}</div>;
}

function RelationshipList({ items, query, focused, selectItem, open }: { items: Relationship[]; query: string; focused: Selection | null; selectItem: (item: Selection) => void; open: (item: Selection) => void }) { const filtered = items.filter((item) => !query || `${item.subject_name} ${item.object_name} ${item.relation_type}`.toLowerCase().includes(query.toLowerCase())); return <div className="relation-list">{filtered.map((item) => { const selection: Selection = { kind: "relationship", id: item.id, title: `${item.subject_name || "Entity"} → ${item.object_name || "Entity"}`, subtitle: item.relation_type || "relationship", data: item }; return <button key={item.id} className={focused?.id === item.id ? "active" : ""} onClick={() => selectItem(selection)} onDoubleClick={() => open(selection)}><span className="relation-glyph"><Waypoints size={15} /></span><span><strong>{item.subject_name || "Entity"} <em>→</em> {item.object_name || "Entity"}</strong><small>{item.relation_type || "relationship"}</small></span><GitBranch size={13} /></button>; })}{!items.length && <SemanticEmpty icon={<Waypoints size={26} />} title="No relationships yet" copy="Connect two narrative objects to make their roles explicit." />}</div>; }
function CanonTable({ facts, query, focused, selectItem, open, projectId, worldId, branchId }: { facts: JsonMap[]; query: string; focused: Selection | null; selectItem: (item: Selection) => void; open: (item: Selection) => void; projectId: string; worldId: string; branchId: string }) { return <div className="fact-table-wrap">{facts.length ? <table className="library-table fact-table"><thead><tr><th>Owner</th><th>Semantic path</th><th>Value</th><th>Status</th><th>Authority</th><th></th></tr></thead><tbody>{facts.filter((fact) => !query || JSON.stringify(fact).toLowerCase().includes(query.toLowerCase())).map((fact) => { const selection: Selection = { kind: "analysis", id: String(fact.id), title: String(fact.path || "Canon fact"), subtitle: String(fact.status || "canon"), data: fact }; return <tr key={String(fact.id)} className={focused?.id === selection.id ? "active" : ""} onClick={() => selectItem(selection)} onDoubleClick={() => open(selection)}><td>{String(fact.owner_type || "world")}</td><td><code>{String(fact.path || "fact")}</code></td><td>{typeof fact.value === "string" ? fact.value : JSON.stringify(fact.value)}</td><td><span className={`status-pill ${String(fact.status || "canon")}`}>{String(fact.status || "canon")}</span></td><td>{String(fact.authority || "user")}</td><td><button onClick={async (event) => { event.stopPropagation(); const newValue = window.prompt("New value", typeof fact.value === "string" ? fact.value : JSON.stringify(fact.value)); if (newValue === null) return; open({ kind: "analysis", title: "Retcon impact", data: await studioApi.retconPreview({ project_id: projectId, world_id: worldId, branch_id: branchId || null, owner_type: String(fact.owner_type), owner_id: String(fact.owner_id), path: String(fact.path), new_value: newValue, note: "retcon from React Library" }) }); }}><Pencil size={12} />Retcon</button></td></tr>; })}</tbody></table> : <SemanticEmpty icon={<Boxes size={26} />} title="No canon facts" copy="Create a fact to track authoritative world state and staged changes." />}</div>; }
function TimelineList({ timeline, query, focused, selectItem, open }: { timeline: JsonMap[]; query: string; focused: Selection | null; selectItem: (item: Selection) => void; open: (item: Selection) => void }) { return <div className="timeline-list">{timeline.filter((event) => !query || JSON.stringify(event).toLowerCase().includes(query.toLowerCase())).map((event, index) => { const selection: Selection = { kind: "analysis", id: String(event.id || index), title: String(event.summary || event.title || "Untitled event"), subtitle: String(event.time_label || "Timeline event"), data: event }; return <article key={selection.id} className={focused?.id === selection.id ? "active" : ""} onClick={() => selectItem(selection)} onDoubleClick={() => open(selection)}><span>{String(event.time_label || `Event ${index + 1}`)}</span><strong>{selection.title}</strong><small>{String(event.event_type || "event")}</small></article>; })}{!timeline.length && <SemanticEmpty icon={<Clock3 size={26} />} title="No timeline events" copy="Add an event to establish chronological and story order." />}</div>; }
function WorldList({ worlds, snapshots, query, focused, worldId, selectItem, open, run, onChanged, setSnapshots }: { worlds: NonNullable<WorldBible["worlds"]>; snapshots: JsonMap[]; query: string; focused: Selection | null; worldId: string; selectItem: (item: Selection) => void; open: (item: Selection) => void; run: (label: string, action: () => Promise<unknown>) => Promise<void>; onChanged: () => Promise<void> | void; setSnapshots: React.Dispatch<React.SetStateAction<JsonMap[]>> }) { return <div className="world-branch-list">{worlds.filter((world) => !query || world.name.toLowerCase().includes(query.toLowerCase())).map((world) => { const selection: Selection = { kind: "world", id: world.id, title: world.name, subtitle: `${world.branches?.length || 0} branches`, data: { world } }; return <article key={world.id} className={focused?.id === world.id ? "active" : ""} onClick={() => selectItem(selection)} onDoubleClick={() => open(selection)}><div><strong>{world.name}</strong><p>{world.description || "No description"}</p><div className="inline-mini-actions">{world.branches?.map((branch) => <button key={branch.id} onClick={(event) => { event.stopPropagation(); selectItem({ kind: "world", id: world.id, title: `${world.name} · ${branch.name}`, data: { world, branch } }); }}>{branch.name}</button>)}</div></div><span>{world.branches?.length || 0} branches</span>{world.id === worldId && <button onClick={async (event) => { event.stopPropagation(); const name = window.prompt("Sandbox name", "What-if"); if (name) await run("Sandbox created", () => studioApi.createSandbox(world.id, name)); }}>Sandbox</button>}</article>; })}<section className="snapshot-strip"><h3>Snapshots</h3>{snapshots.map((snapshot) => <article key={String(snapshot.id)}><span>{String(snapshot.name || snapshot.created_at)}</span><button onClick={async () => { await studioApi.restoreSnapshot(String(snapshot.id)); await onChanged(); }}>Restore</button><button onClick={async () => { await studioApi.deleteSnapshot(String(snapshot.id)); setSnapshots((items) => items.filter((item) => item.id !== snapshot.id)); }}><Trash2 size={12} /></button></article>)}</section></div>; }

function BulkBar({ selected, busy, setSelected, run, onChanged, onSelect }: { selected: string[]; busy: boolean; setSelected: React.Dispatch<React.SetStateAction<string[]>>; run: (label: string, action: () => Promise<unknown>) => Promise<void>; onChanged: () => Promise<void> | void; onSelect: (selection: Selection) => void }) { return <div className="bulk-bar"><strong>{selected.length} selected</strong><button disabled={busy} onClick={async () => { const folderId = window.prompt("Destination folder ID (empty for root)", ""); if (folderId !== null) await run("Moved", () => Promise.all(selected.map((id) => studioApi.updateEntityFamily(id, { folder_id: folderId || null, note: "bulk move" })))); }}>Move</button><button disabled={busy} onClick={async () => { const collectionId = window.prompt("Collection ID"); if (collectionId) await run("Added to collection", () => Promise.all(selected.map((id) => studioApi.linkCollection(collectionId, { resource_type: "entity_family", resource_id: id })))); }}>Collection</button>{selected.length === 2 && <button onClick={async () => { const payload = { source_family_id: selected[0], target_family_id: selected[1] }; onSelect({ kind: "analysis", title: "Entity merge preview", data: await studioApi.mergeEntityPreview(payload) }); if (window.confirm("Apply this merge?")) { await studioApi.mergeEntity(payload); setSelected([]); await onChanged(); } }}>Merge</button>}<button disabled={busy} onClick={() => run("Archived", () => Promise.all(selected.map((id) => studioApi.lifecycle("archive", "entity_family", id))))}><Archive size={13} />Archive</button><button className="danger" disabled={busy} onClick={() => run("Moved to Trash", () => Promise.all(selected.map((id) => studioApi.trash("entity_family", id))))}><Trash2 size={13} />Trash</button><button onClick={() => setSelected([])}>Clear</button></div>; }
function LibraryInspector({ selection, onOpen, onPeek, onContext, compact = false }: { selection: Selection; onOpen: () => void; onPeek: () => void; onContext: () => void; compact?: boolean }) { const data = (selection.data || {}) as JsonMap; const family = (data.family || {}) as JsonMap; const variant = (data.variant || {}) as JsonMap; const highlights = selection.kind === "entity" ? [["Type", family.entity_type || selection.subtitle], ["Status", variant.canon_status || "Shared"], ["Summary", variant.summary || family.description || "No summary yet"]] : [["Type", selection.kind], ["Status", selection.subtitle || "Available"], ["Scope", data.world_id ? "Active world" : "Shared knowledge"]]; return <div className={`library-inspector-body ${compact ? "compact" : ""}`}><div className="inspector-object-mark"><span>{selection.title.slice(0, 1).toUpperCase()}</span><div><strong>{selection.title}</strong><small>{selection.subtitle || selection.kind}</small></div></div><section><h3>Overview</h3>{highlights.map(([label, value]) => <div className="inspector-fact" key={String(label)}><span>{String(label)}</span><strong>{String(value || "—")}</strong></div>)}</section><section><h3>Browse intentionally</h3><p>Inspecting never adds this resource to generation context.</p><div className="inspector-primary-actions"><button onClick={onOpen}><Maximize2 size={13} />Open full sheet</button><button onClick={onPeek}><Eye size={13} />{compact ? "Close peek" : "Peek"}</button></div><button className="add-context-action" onClick={onContext}>Ctrl/⌘ Enter · Add to Chat context</button></section><footer><span>↑↓ browse</span><span>Space peek</span><span>Enter open</span></footer></div>; }
function QuickCreate({ close, text, setText, kind, setKind, entityTypes, preview, busy, previewAction, createAction }: { open: boolean; close: () => void; text: string; setText: (value: string) => void; kind: string; setKind: (value: string) => void; entityTypes: string[]; preview: Record<string, unknown> | null; busy: boolean; previewAction: () => Promise<void>; createAction: () => Promise<void> }) { return <div className="modal-backdrop" onMouseDown={close}><div className="modal quick-modal" onMouseDown={(event) => event.stopPropagation()}><span className="eyebrow">Quick create</span><h2>Describe what you want</h2><p>Arline will infer the right narrative object type.</p><textarea autoFocus value={text} onChange={(event) => setText(event.target.value)} placeholder="Apartment on the third floor, unit A0325…" /><label><span>Force kind</span><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="">Auto detect</option><option value="entity">Entity</option><option value="document">Document</option><option value="project">Project</option><option value="world">World</option>{entityTypes.map((value) => <option key={value} value={`entity:${value}`}>Entity · {value}</option>)}</select></label>{preview && <div className="quick-preview"><span>{String(preview.kind || "resource")}</span><strong>{String(preview.name || text)}</strong><pre>{JSON.stringify(preview, null, 2)}</pre></div>}<div className="modal-actions"><button onClick={close}>Cancel</button><button onClick={() => void previewAction()} disabled={busy || !text.trim()}>Preview</button><button className="primary-action small" onClick={() => void createAction()} disabled={busy || !text.trim()}>{busy ? "Working…" : "Create"}</button></div></div></div>; }
